#! /bin/bash

mkdir -p /services/sshd /var/run/sshd 

cat << EOF | tee /services/sshd/run 
#!/bin/bash
exec /usr/sbin/sshd
EOF

chmod +x /services/sshd/run
sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
