#! /bin/bash

# This script starts a docker container that runs start.sh .
# The name and id and public key of the current user are passed to start.sh 
# so that start.sh can configure a user inside the docker image.

DOCKER_ARGUMENTS=$*

# Technique for start dir thanks to http://stackoverflow.com/a/246128/509928 .

START_SCRIPT=start.sh

SSH_DIR=$HOME/.ssh
RSA_PUB=$SSH_DIR/id_rsa.pub
DSA_PUB=$SSH_DIR/id_dsa.pub

# A ssh key pair is needed.
if [[ ! -e $RSA_PUB && ! -e $DSA_PUB ]]; then
    echo "No public/private .ssh key pairs exist."
    echo "Create a key pair with ssh-keygen before running this script."
    exit 1
fi

if [[ -e $RSA_PUB ]] ; then
    PUBLIC_KEY=$RSA_PUB
fi

if [[ -e $DSA_PUB ]] ; then
    PUBLIC_KEY=$DSA_PUB
fi

USER_NAME=`id -u -n`
USER_ID=`id -u`
USER_KEY=`cat $PUBLIC_KEY`

dockr run --entrypoint /home/builder/workarea/runtime/$START_SCRIPT $DOCKER_ARGUMENTS $USER_NAME $USER_ID "$USER_KEY"
